/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PurchaseOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'packageType' : IDL.Text,
  'timestamp' : IDL.Int,
  'customerEmail' : IDL.Text,
  'selectedCategories' : IDL.Vec(IDL.Text),
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'useCase' : IDL.Text,
  'description' : IDL.Text,
  'monetizationTips' : IDL.Text,
  'beginnerInstructions' : IDL.Text,
});
export const Prompt = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'title' : IDL.Text,
  'promptText' : IDL.Text,
  'section' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategoryById' : IDL.Func([IDL.Text], [Category], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [PurchaseOrder], ['query']),
  'getPromptById' : IDL.Func([IDL.Text], [Prompt], ['query']),
  'getPromptsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Prompt)], ['query']),
  'searchPrompts' : IDL.Func([IDL.Text], [IDL.Vec(Prompt)], ['query']),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'submitOrderWithPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PurchaseOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'packageType' : IDL.Text,
    'timestamp' : IDL.Int,
    'customerEmail' : IDL.Text,
    'selectedCategories' : IDL.Vec(IDL.Text),
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'useCase' : IDL.Text,
    'description' : IDL.Text,
    'monetizationTips' : IDL.Text,
    'beginnerInstructions' : IDL.Text,
  });
  const Prompt = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'title' : IDL.Text,
    'promptText' : IDL.Text,
    'section' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategoryById' : IDL.Func([IDL.Text], [Category], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [PurchaseOrder], ['query']),
    'getPromptById' : IDL.Func([IDL.Text], [Prompt], ['query']),
    'getPromptsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Prompt)], ['query']),
    'searchPrompts' : IDL.Func([IDL.Text], [IDL.Vec(Prompt)], ['query']),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'submitOrderWithPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };