/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'icon' : string,
  'name' : string,
  'useCase' : string,
  'description' : string,
  'monetizationTips' : string,
  'beginnerInstructions' : string,
}
export interface Prompt {
  'id' : string,
  'categoryId' : string,
  'title' : string,
  'promptText' : string,
  'section' : string,
}
export interface PurchaseOrder {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'packageType' : string,
  'timestamp' : bigint,
  'customerEmail' : string,
  'selectedCategories' : Array<string>,
}
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategoryById' : ActorMethod<[string], Category>,
  'getOrderById' : ActorMethod<[string], PurchaseOrder>,
  'getPromptById' : ActorMethod<[string], Prompt>,
  'getPromptsByCategory' : ActorMethod<[string], Array<Prompt>>,
  'searchPrompts' : ActorMethod<[string], Array<Prompt>>,
  'submitOrder' : ActorMethod<[string, string, string, Array<string>], string>,
  'submitOrderWithPayment' : ActorMethod<
    [string, string, string, Array<string>, string, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];