/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PurchaseOrder {
    id: string;
    customerName: string;
    status: string;
    packageType: string;
    timestamp: bigint;
    customerEmail: string;
    selectedCategories: Array<string>;
}
export interface Prompt {
    id: string;
    categoryId: string;
    title: string;
    promptText: string;
    section: string;
}
export interface Category {
    id: string;
    icon: string;
    name: string;
    useCase: string;
    description: string;
    monetizationTips: string;
    beginnerInstructions: string;
}
export interface backendInterface {
    getAllOrders(): Promise<Array<PurchaseOrder>>;
    getCategories(): Promise<Array<Category>>;
    getCategoryById(id: string): Promise<Category>;
    getOrderById(id: string): Promise<PurchaseOrder>;
    getPromptById(id: string): Promise<Prompt>;
    getPromptsByCategory(categoryId: string): Promise<Array<Prompt>>;
    searchPrompts(searchQuery: string): Promise<Array<Prompt>>;
    submitOrder(customerName: string, customerEmail: string, packageType: string, selectedCategories: Array<string>): Promise<string>;
    submitOrderWithPayment(customerName: string, customerEmail: string, packageType: string, selectedCategories: Array<string>, razorpayPaymentId: string, razorpayOrderId: string): Promise<string>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCategoryById(arg0: string): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryById(arg0);
            return result;
        }
    }
    async getOrderById(arg0: string): Promise<PurchaseOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return result;
        }
    }
    async getPromptById(arg0: string): Promise<Prompt> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptById(arg0);
            return result;
        }
    }
    async getPromptsByCategory(arg0: string): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptsByCategory(arg0);
            return result;
        }
    }
    async searchPrompts(arg0: string): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPrompts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPrompts(arg0);
            return result;
        }
    }
    async submitOrder(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitOrderWithPayment(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrderWithPayment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrderWithPayment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
